kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pygeoapi-k8s-manager
nodes:
  - role: control-plane
    # Check
    #     https://github.com/kubernetes-sigs/kind/releases#user-content-new-features
    # for available versions matching you local kubectl version
    image: kindest/node:v1.33.12@sha256:3f5c8443c620245e4d355cfe09e96a91ead32ceaa569d3f1ca9edf0cb2fe2ff4
    extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      protocol: TCP
    - containerPort: 30090
      hostPort: 30090
      protocol: TCP
    - containerPort: 30100
      hostPort: 30100
      protocol: TCP
