kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pygeoapi-k8s-manager
nodes:
  - role: control-plane
    # Check
    #     https://github.com/kubernetes-sigs/kind/releases
    # for available versions matching you local kubectl version
    image: kindest/node:v1.32.11@sha256:5fc52d52a7b9574015299724bd68f183702956aa4a2116ae75a63cb574b35af8
    extraPortMappings:
    - containerPort: 30080
      hostPort: 30080
      protocol: TCP
    - containerPort: 30090
      hostPort: 30090
      protocol: TCP
    - containerPort: 30100
      hostPort: 30100
      protocol: TCP
